name: "Main branch"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:
    name: Unit tests (${{ matrix.name }})
    runs-on: macos-15
    strategy:
      matrix:
        include:
        - name: iOS
          destination: platform=iOS Simulator,OS=18.5,name=iPhone 16
        - name: macOS
          destination: platform=macOS
        - name: tvOS
          destination: platform=tvOS Simulator,OS=18.5,name=Apple TV 4K (3rd generation)
        - name: visionOS
          destination: platform=visionOS Simulator,OS=2.5,name=Apple Vision Pro
        - name: watchOS
          destination: platform=watchOS Simulator,OS=11.5,name=Apple Watch Series 10 (42mm)
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app
    - name: Build and run tests
      run: xcrun xcodebuild test -scheme TMDB -resultBundlePath Artifacts/TestResults.xcresult -destination "${{ matrix.destination }}" CODE_SIGNING_ALLOWED=NO SWIFT_TREAT_WARNINGS_AS_ERRORS=YES
    - name: Upload xcresult bundle
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts (${{ matrix.name }})
        path: Artifacts
