name: "Main branch"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    concurrency:
      group: MainBranch-${{ matrix.name }}-${{ github.ref }}
      cancel-in-progress: true
    name: Analyze code (${{ matrix.name }})
    runs-on: macos-15
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - destination: platform=iOS Simulator,OS=18.5,name=iPhone 16
          name: iOS
        - destination: platform=macOS
          name: macOS
        - destination: platform=tvOS Simulator,OS=18.5,name=Apple TV 4K (3rd generation)
          name: tvOS
        - destination: platform=watchOS Simulator,OS=11.5,name=Apple Watch Series 10 (42mm)
          name: watchOS
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: swift
        build-mode: manual
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app
    - name: Build and run tests
      shell: bash
      run: xcrun xcodebuild clean test -scheme TMDB  -resultBundlePath TestResults -destination "${{ matrix.destination }}" CODE_SIGNING_ALLOWED="NO"
    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:swift"
    - name: Upload xcresult bundle
      uses: actions/upload-artifact@v4
      with:
        name: TestResults-${{ matrix.name }}
        path: TestResults.xcresult
